# Generated by Django 4.2.5 on 2023-09-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalMetaData',
            fields=[
                ('Area', models.IntegerField()),
                ('HOSP_ID', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('HOSP_NAME', models.CharField(max_length=255)),
                ('HOSP_ADDRESS', models.TextField()),
                ('AREA_CODE', models.CharField(max_length=10)),
                ('PHONE_NUMBER', models.CharField(max_length=15)),
                ('HOSP_CNT_TYPE', models.CharField(max_length=100)),
                ('HOSP_TYPE', models.CharField(max_length=100)),
                ('HOSP_ATTR_TYPE', models.CharField(max_length=100)),
                ('CONT_E_DATE', models.DateField(blank=True, null=True)),
                ('OPEN_STATUS', models.CharField(max_length=50)),
                ('CONT_S_DATE', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
