# Generated by Django 4.2.5 on 2023-09-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('area_code', models.IntegerField(verbose_name='分區別')),
                ('hospital_id', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='醫事機構代碼')),
                ('hospital_name', models.CharField(max_length=255, verbose_name='醫事機構名稱')),
                ('address', models.TextField(verbose_name='機構地址')),
                ('phone_area_code', models.CharField(max_length=5, verbose_name='電話區域號碼')),
                ('phone_number', models.CharField(max_length=20, verbose_name='電話號碼')),
                ('contract_type', models.CharField(max_length=5, verbose_name='特約類別')),
                ('type_code', models.CharField(max_length=5, verbose_name='型態別')),
                ('hospital_category', models.CharField(max_length=5, verbose_name='醫事機構種類')),
                ('contract_end_date', models.DateField(blank=True, null=True, verbose_name='終止合約或歇業日期')),
                ('operation_status', models.CharField(max_length=5, verbose_name='開業狀況')),
                ('contract_start_date', models.DateField(verbose_name='原始合約起日')),
            ],
        ),
        migrations.DeleteModel(
            name='HospitalMetaData',
        ),
    ]
